from django.urls import path
from . import views

app_name = 'P0200ExcelDownload'
urlpatterns = [
    ### path('', views.index_view, name='index_view'), 
    path('data_type/<slug:data_type>/', views.index_view, name='index_view'), 

    path('building/', views.building_view, name='building_view'), 
    path('ken/', views.ken_view, name='ken_view'), 
    path('city/', views.city_view, name='city_view'), 
    path('kasen_kaigan/', views.kasen_kaigan_view, name='kasen_kaigan_view'), 
    path('suikei/', views.suikei_view, name='suikei_view'), 
    path('suikei_type/', views.suikei_type_view, name='suikei_type_view'), 
    path('kasen/', views.kasen_view, name='kasen_view'), 
    path('kasen_type/', views.kasen_type_view, name='kasen_type_view'), 
    path('cause/', views.cause_view, name='cause_view'), 
    path('underground/', views.underground_view, name='underground_view'), 
    path('usage/', views.usage_view, name='usage_view'), 
    path('flood_sediment/', views.flood_sediment_view, name='flood_sediment_view'), 
    path('gradient/', views.gradient_view, name='gradient_view'), 
    path('industry/', views.industry_view, name='industry_view'), 
    path('house_asset/', views.house_asset_view, name='house_asset_view'), 
    path('house_rate/', views.house_rate_view, name='house_rate_view'), 
    path('house_alt/', views.house_alt_view, name='house_alt_view'), 
    path('house_clean/', views.house_clean_view, name='house_clean_view'), 
    path('household_asset/', views.household_asset_view, name='household_asset_view'), 
    path('household_rate/', views.household_rate_view, name='household_rate_view'), 
    path('car_asset/', views.car_asset_view, name='car_asset_view'), 
    path('car_rate/', views.car_rate_view, name='car_rate_view'), 
    path('office_asset/', views.office_asset_view, name='office_asset_view'), 
    path('office_rate/', views.office_rate_view, name='office_rate_view'), 
    path('office_suspend/', views.office_suspend_view, name='office_suspend_view'), 
    path('office_stagnate/', views.office_stagnate_view, name='office_stagnate_view'), 
    path('office_alt/', views.office_alt_view, name='office_alt_view'), 
    path('farmer_fisher_asset/', views.farmer_fisher_asset_view, name='farmer_fisher_asset_view'), 
    path('farmer_fisher_rate/', views.farmer_fisher_rate_view, name='farmer_fisher_rate_view'), 
    path('area/', views.area_view, name='area_view'), 
    path('weather/', views.weather_view, name='weather_view'), 
    path('suigai/', views.suigai_view, name='suigai_view'), 
    path('ippan/', views.ippan_view, name='ippan_view'), 
    path('ippan_view/', views.ippan_view_view, name='ippan_view_view'), 
    path('ippan_summary/', views.ippan_summary_view, name='ippan_summary_view'), 
    path('ippan_group_by_ken/', views.ippan_group_by_ken_view, name='ippan_group_by_ken_view'), 
    path('ippan_group_by_suikei/', views.ippan_group_by_suikei_view, name='ippan_group_by_suikei'), 

    path('ippan_chosa/', views.ippan_chosa_view, name='ippan_chosa_view'), 
    path('ippan_city/', views.ippan_city_view, name='ippan_city_view'), 
    path('ippan_ken/', views.ippan_ken_view, name='ippan_ken_view'), 
    
    path('building/lock/<slug:lock>/', views.building_view, name='building_view'), 
    path('ken/lock/<slug:lock>/', views.ken_view, name='ken_view'), 
    path('city/lock/<slug:lock>/', views.city_view, name='city_view'), 
    path('kasen_kaigan/lock/<slug:lock>/', views.kasen_kaigan_view, name='kasen_kaigan_view'), 
    path('suikei/lock/<slug:lock>/', views.suikei_view, name='suikei_view'), 
    path('suikei_type/lock/<slug:lock>/', views.suikei_type_view, name='suikei_type_view'), 
    path('kasen/lock/<slug:lock>/', views.kasen_view, name='kasen_view'), 
    path('kasen_type/lock/<slug:lock>/', views.kasen_type_view, name='kasen_type_view'), 
    path('cause/lock/<slug:lock>/', views.cause_view, name='cause_view'), 
    path('underground/lock/<slug:lock>/', views.underground_view, name='underground_view'), 
    path('usage/lock/<slug:lock>/', views.usage_view, name='usage_view'), 
    path('flood_sediment/lock/<slug:lock>/', views.flood_sediment_view, name='flood_sediment_view'), 
    path('gradient/lock/<slug:lock>/', views.gradient_view, name='gradient_view'), 
    path('industry/lock/<slug:lock>/', views.industry_view, name='industry_view'), 
    path('house_asset/lock/<slug:lock>/', views.house_asset_view, name='house_asset_view'), 
    path('house_rate/lock/<slug:lock>/', views.house_rate_view, name='house_rate_view'), 
    path('house_alt/lock/<slug:lock>/', views.house_alt_view, name='house_alt_view'), 
    path('house_clean/lock/<slug:lock>/', views.house_clean_view, name='house_clean_view'), 
    path('household_asset/lock/<slug:lock>/', views.household_asset_view, name='household_asset_view'), 
    path('household_rate/lock/<slug:lock>/', views.household_rate_view, name='household_rate_view'), 
    path('car_asset/lock/<slug:lock>/', views.car_asset_view, name='car_asset_view'), 
    path('car_rate/lock/<slug:lock>/', views.car_rate_view, name='car_rate_view'), 
    path('office_asset/lock/<slug:lock>/', views.office_asset_view, name='office_asset_view'), 
    path('office_rate/lock/<slug:lock>/', views.office_rate_view, name='office_rate_view'), 
    path('office_suspend/lock/<slug:lock>/', views.office_suspend_view, name='office_suspend_view'), 
    path('office_stagnate/lock/<slug:lock>/', views.office_stagnate_view, name='office_stagnate_view'), 
    path('office_alt/lock/<slug:lock>/', views.office_alt_view, name='office_alt_view'), 
    path('farmer_fisher_asset/lock/<slug:lock>/', views.farmer_fisher_asset_view, name='farmer_fisher_asset_view'), 
    path('farmer_fisher_rate/lock/<slug:lock>/', views.farmer_fisher_rate_view, name='farmer_fisher_rate_view'), 
    path('area/lock/<slug:lock>/', views.area_view, name='area_view'), 
    path('weather/lock/<slug:lock>/', views.weather_view, name='weather_view'), 
    path('suigai/lock/<slug:lock>/', views.suigai_view, name='suigai_view'), 
    path('ippan/lock/<slug:lock>/', views.ippan_view, name='ippan_view'), 
    path('ippan_view/lock/<slug:lock>/', views.ippan_view_view, name='ippan_view_view'), 
    path('ippan_summary/lock/<slug:lock>/', views.ippan_summary_view, name='ippan_summary_view'), 
    path('ippan_group_by_ken/lock/<slug:lock>/', views.ippan_group_by_ken_view, name='ippan_group_by_ken_view'), 
    path('ippan_group_by_suikei/lock/<slug:lock>/', views.ippan_group_by_suikei_view, name='ippan_group_by_suikei'), 

    path('ippan_chosa/lock/<slug:lock>/', views.ippan_chosa_view, name='ippan_chosa_view'), 
    path('ippan_city/lock/<slug:lock>/', views.ippan_city_view, name='ippan_city_view'), 
    path('ippan_ken/lock/<slug:lock>/', views.ippan_ken_view, name='ippan_ken_view'), 
    
    path('download/<slug:hash_code>/<slug:count>/', views.download_view, name='download_view'), 
]
