# Generated by Django 4.0.3 on 2022-04-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P0200ExcelDownload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='P0200Citys',
            new_name='P0200City',
        ),
        migrations.RenameModel(
            old_name='P0200Prefectures',
            new_name='P0200Prefecture',
        ),
    ]
