# Generated by Django 4.0.3 on 2022-04-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P0200ExcelDownload', '0002_rename_p0200citys_p0200city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CITY',
            fields=[
                ('CODE', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('KEN_CODE', models.CharField(max_length=2)),
                ('NAME', models.CharField(max_length=200)),
                ('POPULATION', models.IntegerField()),
                ('AREA', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ENGAN',
            fields=[
                ('CODE', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KASEN',
            fields=[
                ('CODE', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('SUIKEI_CODE', models.CharField(max_length=3)),
                ('NAME', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KEN',
            fields=[
                ('CODE', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SUIKEI',
            fields=[
                ('CODE', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=200)),
            ],
        ),
    ]
