INSERT INTO UNDERGROUND (UNDERGROUND_CODE, UNDERGROUND_NAME) VALUES ('1','地上のみ');
INSERT INTO UNDERGROUND (UNDERGROUND_CODE, UNDERGROUND_NAME) VALUES ('2','地上部分');
INSERT INTO UNDERGROUND (UNDERGROUND_CODE, UNDERGROUND_NAME) VALUES ('3','地下部分');
INSERT INTO UNDERGROUND (UNDERGROUND_CODE, UNDERGROUND_NAME) VALUES ('4','地下のみ');
