INSERT INTO STATUS(STATUS_CODE, STATUS_NAME) VALUES ('RUNNING','実行中');
INSERT INTO STATUS(STATUS_CODE, STATUS_NAME) VALUES ('CANCEL','キャンセル');
INSERT INTO STATUS(STATUS_CODE, STATUS_NAME) VALUES ('SUCCESS','成功');
INSERT INTO STATUS(STATUS_CODE, STATUS_NAME) VALUES ('FAILURE','失敗');
INSERT INTO STATUS(STATUS_CODE, STATUS_NAME) VALUES ('WAITING','待機中');
