INSERT INTO P0200ExcelDownload_BUILDING (BUILDING_CODE, BUILDING_NAME) VALUES ('1','戸建住宅');
INSERT INTO P0200ExcelDownload_BUILDING (BUILDING_CODE, BUILDING_NAME) VALUES ('2','共同住宅');
INSERT INTO P0200ExcelDownload_BUILDING (BUILDING_CODE, BUILDING_NAME) VALUES ('3','事業所併用住宅');
INSERT INTO P0200ExcelDownload_BUILDING (BUILDING_CODE, BUILDING_NAME) VALUES ('4','事業所');
INSERT INTO P0200ExcelDownload_BUILDING (BUILDING_CODE, BUILDING_NAME) VALUES ('5','その他建物');
INSERT INTO P0200ExcelDownload_BUILDING (BUILDING_CODE, BUILDING_NAME) VALUES ('6','建物以外');
