INSERT INTO P0000Common_SUIKEI_TYPE(SUIKEI_TYPE_CODE, SUIKEI_TYPE_NAME) VALUES ('1','一級');
INSERT INTO P0000Common_SUIKEI_TYPE(SUIKEI_TYPE_CODE, SUIKEI_TYPE_NAME) VALUES ('2','二級');
INSERT INTO P0000Common_SUIKEI_TYPE(SUIKEI_TYPE_CODE, SUIKEI_TYPE_NAME) VALUES ('3','準用');
INSERT INTO P0000Common_SUIKEI_TYPE(SUIKEI_TYPE_CODE, SUIKEI_TYPE_NAME) VALUES ('4','普通');
INSERT INTO P0000Common_SUIKEI_TYPE(SUIKEI_TYPE_CODE, SUIKEI_TYPE_NAME) VALUES ('5','沿岸');
INSERT INTO P0000Common_SUIKEI_TYPE(SUIKEI_TYPE_CODE, SUIKEI_TYPE_NAME) VALUES ('6','河川海岸以外');
