INSERT INTO KASEN_TYPE (KASEN_TYPE_CODE, KASEN_TYPE_NAME) VALUES ('1','直轄');
INSERT INTO KASEN_TYPE (KASEN_TYPE_CODE, KASEN_TYPE_NAME) VALUES ('2','指定');
INSERT INTO KASEN_TYPE (KASEN_TYPE_CODE, KASEN_TYPE_NAME) VALUES ('3','二級');
INSERT INTO KASEN_TYPE (KASEN_TYPE_CODE, KASEN_TYPE_NAME) VALUES ('4','準用');
INSERT INTO KASEN_TYPE (KASEN_TYPE_CODE, KASEN_TYPE_NAME) VALUES ('5','普通');
INSERT INTO KASEN_TYPE (KASEN_TYPE_CODE, KASEN_TYPE_NAME) VALUES ('6','海岸');
INSERT INTO KASEN_TYPE (KASEN_TYPE_CODE, KASEN_TYPE_NAME) VALUES ('7','河川海岸以外');
