INSERT INTO P0200ExcelDownload_FLOOD_SEDIMENT (FLOOD_SEDIMENT_CODE, FLOOD_SEDIMENT_NAME) VALUES ('1','浸水');
INSERT INTO P0200ExcelDownload_FLOOD_SEDIMENT (FLOOD_SEDIMENT_CODE, FLOOD_SEDIMENT_NAME) VALUES ('2','土砂');
