INSERT INTO P0200ExcelDownload_UNDERGROUND (UNDERGROUND_CODE, UNDERGROUND_NAME) VALUES ('1','地上のみ');
INSERT INTO P0200ExcelDownload_UNDERGROUND (UNDERGROUND_CODE, UNDERGROUND_NAME) VALUES ('2','地上部分');
INSERT INTO P0200ExcelDownload_UNDERGROUND (UNDERGROUND_CODE, UNDERGROUND_NAME) VALUES ('3','地下部分');
