-- HOKKAIDO:01
-- SELECT ippan_id FROM ippan_view WHERE ken_code='01' ORDER BY ippan_id;

DELETE FROM IPPAN_SUMMARY IS1 USING IPPAN_VIEW IV1 WHERE IS1.ippan_id = IV1.ippan_id AND IV1.ken_code='01';

INSERT INTO IPPAN_SUMMARY (
    ippan_id, 
    suigai_id, 
    house_summary_lv00, 
    house_summary_lv01_49, 
    house_summary_lv50_99, 
    house_summary_lv100, 
    house_summary_half, 
    house_summary_full, 
    household_summary_lv00, 
    household_summary_lv01_49, 
    household_summary_lv50_99, 
    household_summary_lv100, 
    household_summary_half, 
    household_summary_full, 
    car_summary_lv00, 
    car_summary_lv01_49, 
    car_summary_lv50_99, 
    car_summary_lv100, 
    car_summary_half, 
    car_summary_full, 
    house_alt_summary_lv00, 
    house_alt_summary_lv01_49, 
    house_alt_summary_lv50_99, 
    house_alt_summary_lv100, 
    house_alt_summary_half, 
    house_alt_summary_full, 
    house_clean_summary_lv00, 
    house_clean_summary_lv01_49, 
    house_clean_summary_lv50_99, 
    house_clean_summary_lv100, 
    house_clean_summary_half, 
    house_clean_summary_full, 
    office_dep_summary_lv00, 
    office_dep_summary_lv01_49, 
    office_dep_summary_lv50_99, 
    office_dep_summary_lv100, 
    -- office_dep_summary_half, 
    office_dep_summary_full, 
    office_inv_summary_lv00, 
    office_inv_summary_lv01_49, 
    office_inv_summary_lv50_99, 
    office_inv_summary_lv100, 
    -- office_inv_summary_half, 
    office_inv_summary_full, 
    office_sus_summary_lv00, 
    office_sus_summary_lv01_49, 
    office_sus_summary_lv50_99, 
    office_sus_summary_lv100, 
    -- office_sus_summary_half, 
    office_sus_summary_full, 
    office_stg_summary_lv00, 
    office_stg_summary_lv01_49, 
    office_stg_summary_lv50_99, 
    office_stg_summary_lv100, 
    -- office_stg_summary_half, 
    office_stg_summary_full, 
    farmer_fisher_dep_summary_lv00, 
    farmer_fisher_dep_summary_lv01_49, 
    farmer_fisher_dep_summary_lv50_99, 
    farmer_fisher_dep_summary_lv100, 
    -- farmer_fisher_dep_summary_half, 
    farmer_fisher_dep_summary_full, 
    farmer_fisher_inv_summary_lv00, 
    farmer_fisher_inv_summary_lv01_49, 
    farmer_fisher_inv_summary_lv50_99, 
    farmer_fisher_inv_summary_lv100, 
    -- farmer_fisher_inv_summary_half, 
    farmer_fisher_inv_summary_full, 
    office_alt_summary_lv00, 
    office_alt_summary_lv01_49, 
    office_alt_summary_lv50_99, 
    office_alt_summary_lv100, 
    office_alt_summary_half, 
    office_alt_summary_full 
) 
SELECT 
    IV1.ippan_id AS ippan_id, 
    IV1.suigai_id AS suigai_id, 
    IV1.floor_area_lv00 * HA1.house_asset * HR1.house_rate_lv00 AS house_summary_lv00, 
    IV1.floor_area_lv01_49 * HA1.house_asset * HR1.house_rate_lv00_50 AS house_summary_lv01_49, 
    IV1.floor_area_lv50_99 * HA1.house_asset * HR1.house_rate_lv50_100 AS house_summary_lv50_99, 
    IV1.floor_area_lv100 * HA1.house_asset * HR1.house_rate_lv100_200 AS house_summary_lv100, 
    IV1.floor_area_half * HA1.house_asset * HR1.house_rate_lv200_300 AS house_summary_half, 
    IV1.floor_area_full * HA1.house_asset * HR1.house_rate_lv300 AS house_summary_full, 
    IV1.family_lv00 * HHA1.household_asset * HHR1.household_rate_lv00 AS household_summary_lv00, 
    IV1.family_lv01_49 * HHA1.household_asset * HHR1.household_rate_lv00_50 AS household_summary_lv01_49, 
    IV1.family_lv50_99 * HHA1.household_asset * HHR1.household_rate_lv50_100 AS household_summary_lv50_99, 
    IV1.family_lv100 * HHA1.household_asset * HHR1.household_rate_lv100_200 AS household_summary_lv100, 
    IV1.family_half * HHA1.household_asset * HHR1.household_rate_lv200_300 AS household_summary_half, 
    IV1.family_full * HHA1.household_asset * HHR1.household_rate_lv300 AS household_summary_full, 
    IV1.family_lv00 * CA1.car_asset * CR1.car_rate_lv00 AS car_summary_lv00, 
    IV1.family_lv01_49 * CA1.car_asset * CR1.car_rate_lv00_50 AS car_summary_lv01_49, 
    IV1.family_lv50_99 * CA1.car_asset * CR1.car_rate_lv50_100 AS car_summary_lv50_99, 
    IV1.family_lv100 * CA1.car_asset * CR1.car_rate_lv100_200 AS car_summary_lv100, 
    IV1.family_half * CA1.car_asset * CR1.car_rate_lv200_300 AS car_summary_half, 
    IV1.family_full * CA1.car_asset * CR1.car_rate_lv300 AS car_summary_full, 
    IV1.family_lv00 * HALT1.house_alt_lv00 AS house_alt_summary_lv00, 
    IV1.family_lv01_49 * HALT1.house_alt_lv00_50 AS house_alt_summary_lv01_49, 
    IV1.family_lv50_99 * HALT1.house_alt_lv50_100 AS house_alt_summary_lv50_99, 
    IV1.family_lv100 * HALT1.house_alt_lv100_200 AS house_alt_summary_lv100, 
    IV1.family_half * HALT1.house_alt_lv200_300 AS house_alt_summary_half, 
    IV1.family_full * HALT1.house_alt_lv300 AS house_alt_summary_full, 
    IV1.family_lv00 * HCL1.house_clean_days_lv00 * HCL1.house_clean_unit_cost AS house_clean_summary_lv00, 
    IV1.family_lv01_49 * HCL1.house_clean_days_lv00 * HCL1.house_clean_unit_cost AS house_clean_summary_lv01_49, 
    IV1.family_lv50_99 * HCL1.house_clean_days_lv00 * HCL1.house_clean_unit_cost AS house_clean_summary_lv50_99, 
    IV1.family_lv100 * HCL1.house_clean_days_lv00 * HCL1.house_clean_unit_cost AS house_clean_summary_lv100, 
    IV1.family_half * HCL1.house_clean_days_lv00 * HCL1.house_clean_unit_cost AS house_clean_summary_half, 
    IV1.family_full * HCL1.house_clean_days_lv00 * HCL1.house_clean_unit_cost AS house_clean_summary_full, 
    IV1.employee_lv00 * OA1.office_dep_asset * OR1.office_dep_rate_lv00 AS office_dep_summary_lv00, 
    IV1.employee_lv01_49 * OA1.office_dep_asset * OR1.office_dep_rate_lv00_50 AS office_dep_summary_lv01_49, 
    IV1.employee_lv50_99 * OA1.office_dep_asset * OR1.office_dep_rate_lv50_100 AS office_dep_summary_lv50_99, 
    IV1.employee_lv100 * OA1.office_dep_asset * OR1.office_dep_rate_lv100_200 AS office_dep_summary_lv100, 
    -- IV1.employee_half * OA1.office_dep_asset * OR1.office_dep_rate_lv200_300 AS office_dep_summary_half, 
    IV1.employee_full * OA1.office_dep_asset * OR1.office_dep_rate_lv300 AS office_dep_summary_full, 
    IV1.employee_lv00 * OA1.office_inv_asset * OR1.office_inv_rate_lv00 AS office_inv_summary_lv00, 
    IV1.employee_lv01_49 * OA1.office_inv_asset * OR1.office_inv_rate_lv00_50 AS office_inv_summary_lv01_49, 
    IV1.employee_lv50_99 * OA1.office_inv_asset * OR1.office_inv_rate_lv50_100 AS office_inv_summary_lv50_99, 
    IV1.employee_lv100 * OA1.office_inv_asset * OR1.office_inv_rate_lv100_200 AS office_inv_summary_lv100, 
    -- IV1.employee_half * OA1.office_inv_asset * OR1.office_inv_rate_lv200_300 AS office_inv_summary_half, 
    IV1.employee_full * OA1.office_inv_asset * OR1.office_inv_rate_lv300 AS office_inv_summary_full, 
    IV1.employee_lv00 * OA1.office_va_asset * OSUS1.office_sus_days_lv00 AS office_sus_summary_lv00, 
    IV1.employee_lv01_49 * OA1.office_va_asset * OSUS1.office_sus_days_lv00_50 AS office_sus_summary_lv00_50, 
    IV1.employee_lv50_99 * OA1.office_va_asset * OSUS1.office_sus_days_lv50_100 AS office_sus_summary_lv50_100, 
    IV1.employee_lv100 * OA1.office_va_asset * OSUS1.office_sus_days_lv100_200 AS office_sus_summary_lv100_200, 
    -- IV1.employee_half * OA1.office_va_asset * OSUS1.office_sus_days_lv200_300 AS office_sus_summary_lv200_300, 
    IV1.employee_full * OA1.office_va_asset * OSUS1.office_sus_days_lv300 AS office_sus_summary_lv300, 
    IV1.employee_lv00 * OA1.office_va_asset * OSTG1.office_stg_days_lv00 / 2.0 AS office_stg_summary_lv00, 
    IV1.employee_lv01_49 * OA1.office_va_asset * OSTG1.office_stg_days_lv00_50 / 2.0 AS office_stg_summary_lv01_49, 
    IV1.employee_lv50_99 * OA1.office_va_asset * OSTG1.office_stg_days_lv50_100 / 2.0 AS office_stg_summary_lv50_99, 
    IV1.employee_lv100 * OA1.office_va_asset * OSTG1.office_stg_days_lv100_200 / 2.0 AS office_stg_summary_lv100, 
    -- IV1.employee_half * OA1.office_va_asset * OSTG1.office_stg_days_lv200_300 / 2.0 AS office_stg_summary_half, 
    IV1.employee_full * OA1.office_va_asset * OSTG1.office_stg_days_lv300 / 2.0 AS office_stg_summary_full, 
    IV1.farmer_fisher_lv00 * FFA1.farmer_fisher_dep_asset * FFR1.farmer_fisher_dep_rate_lv00 AS farmer_fisher_dep_summary_lv00, 
    IV1.farmer_fisher_lv01_49 * FFA1.farmer_fisher_dep_asset * FFR1.farmer_fisher_dep_rate_lv00_50 AS farmer_fisher_dep_summary_lv01_49, 
    IV1.farmer_fisher_lv50_99 * FFA1.farmer_fisher_dep_asset * FFR1.farmer_fisher_dep_rate_lv50_100 AS farmer_fisher_dep_summary_lv50_99, 
    IV1.farmer_fisher_lv100 * FFA1.farmer_fisher_dep_asset * FFR1.farmer_fisher_dep_rate_lv100_200 AS farmer_fisher_dep_summary_lv100, 
    --IV1.farmer_fisher_half * FFA1.farmer_fisher_dep_asset * FFR1.farmer_fisher_dep_rate_lv200_300 AS farmer_fisher_dep_summary_half, 
    IV1.farmer_fisher_full * FFA1.farmer_fisher_dep_asset * FFR1.farmer_fisher_dep_rate_lv300 AS farmer_fisher_dep_summary_full, 
    IV1.farmer_fisher_lv00 * FFA1.farmer_fisher_inv_asset * FFR1.farmer_fisher_inv_rate_lv00 AS farmer_fisher_inv_summary_lv00, 
    IV1.farmer_fisher_lv01_49 * FFA1.farmer_fisher_inv_asset * FFR1.farmer_fisher_inv_rate_lv00_50 AS farmer_fisher_inv_summary_lv01_49, 
    IV1.farmer_fisher_lv50_99 * FFA1.farmer_fisher_inv_asset * FFR1.farmer_fisher_inv_rate_lv50_100 AS farmer_fisher_inv_summary_lv50_99, 
    IV1.farmer_fisher_lv100 * FFA1.farmer_fisher_inv_asset * FFR1.farmer_fisher_inv_rate_lv100_200 AS farmer_fisher_inv_summary_lv100, 
    -- IV1.farmer_fisher_half * FFA1.farmer_fisher_inv_asset * FFR1.farmer_fisher_inv_rate_lv200_300 AS farmer_fisher_inv_summary_half, 
    IV1.farmer_fisher_full * FFA1.farmer_fisher_inv_asset * FFR1.farmer_fisher_inv_rate_lv300 AS farmer_fisher_inv_summary_full, 
    IV1.office_lv00 * OALT1.office_alt_lv00 AS office_alt_summary_lv00, 
    IV1.office_lv01_49 * OALT1.office_alt_lv00_50 AS office_alt_summary_lv01_49, 
    IV1.office_lv50_99 * OALT1.office_alt_lv50_100 AS office_alt_summary_lv50_99, 
    IV1.office_lv100 * OALT1.office_alt_lv100_200 AS office_alt_summary_lv100, 
    IV1.office_half * OALT1.office_alt_lv200_300 AS office_alt_summary_half, 
    IV1.office_full * OALT1.office_alt_lv300 AS office_alt_summary_full 
FROM 
    IPPAN_VIEW IV1 
    LEFT JOIN HOUSE_ASSET HA1 ON IV1.ken_code = HA1.ken_code 
    LEFT JOIN HOUSE_RATE HR1 ON IV1.flood_sediment_code = HR1.flood_sediment_code AND IV1.gradient_code = HR1.gradient_code 
    LEFT JOIN HOUSEHOLD_RATE HHR1 ON IV1.flood_sediment_code = HHR1.flood_sediment_code 
    LEFT JOIN OFFICE_ASSET OA1 ON IV1.industry_code = OA1.industry_code 
    LEFT JOIN OFFICE_RATE OR1 ON IV1.flood_sediment_code = OR1.flood_sediment_code 
    LEFT JOIN FARMER_FISHER_RATE FFR1 ON IV1.flood_sediment_code = FFR1.flood_sediment_code, 
    HOUSEHOLD_ASSET HHA1, 
    CAR_ASSET CA1, 
    CAR_RATE CR1, 
    HOUSE_ALT HALT1, 
    HOUSE_CLEAN HCL1, 
    OFFICE_SUSPEND OSUS1, 
    OFFICE_STAGNATE OSTG1, 
    FARMER_FISHER_ASSET FFA1, 
    OFFICE_ALT OALT1 
WHERE IV1.ken_code = '01' 
ORDER BY CAST(IV1.ippan_id AS INTEGER)
;