INSERT INTO P0000Common_USAGE (USAGE_CODE, USAGE_NAME) VALUES ('1','住居');
INSERT INTO P0000Common_USAGE (USAGE_CODE, USAGE_NAME) VALUES ('2','事業所');
INSERT INTO P0000Common_USAGE (USAGE_CODE, USAGE_NAME) VALUES ('3','地下街');
INSERT INTO P0000Common_USAGE (USAGE_CODE, USAGE_NAME) VALUES ('4','その他');
