INSERT INTO P0200ExcelDownload_KASEN_KAIGAN (KASEN_KAIGAN_CODE, KASEN_KAIGAN_NAME) VALUES ('1','河川');
INSERT INTO P0200ExcelDownload_KASEN_KAIGAN (KASEN_KAIGAN_CODE, KASEN_KAIGAN_NAME) VALUES ('2','海岸');
INSERT INTO P0200ExcelDownload_KASEN_KAIGAN (KASEN_KAIGAN_CODE, KASEN_KAIGAN_NAME) VALUES ('3','河川海岸以外');
